version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    volumes:
      - ./containers_data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  web:
    build: .
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  frontend:
    build: ./front
    tty: true
    ports:
      - 8000:3000
    command: yarn dev
    volumes:
      - .:/app